In [327]:
#load the dataset
import pandas as pd

path = r"C:\Users\User\Documents\Python datasets\ds_salaries_dirty.xlsx"
df = pd.read_excel(path)

### Task 1: Clean and Validate the Salary Data

In [328]:
# Examining the dataset
df.head()

,work_year,experience_level,employment_type,job_title,salary_in_usd,remote_ratio,company_location,company_size
0,2022,SE,CT,Data Scientist,42183.0,50,IN,L
1,2023,MI,FL,Data Scientist,190371.0,100,IN,S
2,2020,MI,CT,DS,173946.0,50,IN,L
3,2022,NaN,FT,ML Engineer,146336.0,50,DE,S
4,2022,MI,FL,ML Engineer,9999999.0,100,NG,L

In [329]:
df.shape

(100, 8)

In [330]:
# Getting info about null values and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   work_year         100 non-null    int64
 1   experience_level  90 non-null     object
 2   employment_type   92 non-null     object
 3   job_title         100 non-null    object
 4   salary_in_usd     96 non-null     float64
 5   remote_ratio      100 non-null    int64
 6   company_location  94 non-null     object
 7   company_size      100 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 6.4+ KB

#### Work_year

In [331]:
# Checking if there are odd/bizarre values in work_year column. None found.
df.work_year.unique()

array([2022, 2023, 2020, 2021], dtype=int64)

#### Experience_level

In [332]:
df.experience_level.value_counts()

experience_level
SE    28
EN    23
EX    21
MI    18
Name: count, dtype: int64

In [333]:
# Replace null values
df['experience_level'].fillna(value='EN', inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_11136\619993092.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['experience_level'].fillna(value='EN', inplace=True)

#### Employment_type

In [334]:
df['employment_type'].fillna(value='FT', inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_11136\1928784314.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['employment_type'].fillna(value='FT', inplace=True)

#### Job_title

In [335]:
df.job_title.value_counts()

job_title
AI Specialist     32
Data Analyst      24
Data Scientist    21
ML Engineer       18
DS                 5
Name: count, dtype: int64

In [336]:
# remove entry with less than 3 characters, then reindex
df = df[~(df['job_title'] == 'DS')]
df.reset_index(inplace = True)

In [337]:
# drop the indeex column that was added during reindexing
df.drop(columns = 'index', inplace = True)

#### Salary_in_usd

In [338]:
#replace salary_in_usd values below 10,000 or above 1,000,000 with median.
median_salary = df.salary_in_usd.median()
df.loc[df['salary_in_usd'] < 10000, 'salary_in_usd'] = median_salary
df.loc[df['salary_in_usd'] > 1000000, 'salary_in_usd'] = median_salary

In [339]:
# It appears that there are 4 null values in salary_in_usd. Replace with median below. Median is preferred to mean due to possible outliers.
# Also, these columns are not being dropped because they are only 4 and so replacing them would cause little or no bias.
df['salary_in_usd'] = df['salary_in_usd'].fillna(median_salary)

#### Company_location

In [340]:
#checking for invalid entries
df.company_location.value_counts()

company_location
IN    23
GB    22
NG    17
US    16
DE    12
Name: count, dtype: int64

In [341]:
df.company_location.unique()

array(['IN', 'DE', 'NG', 'GB', nan, 'US'], dtype=object)

In [342]:
# replace missing values in company_location with 'US'
df['company_location'] = df['company_location'].fillna(value = 'US')

In [343]:
# replace the invalid entry in company_location with 'US'
df.loc[df['company_location'] == '154019.0', 'company_location'] = 'US'

#### Company_size

In [344]:
# checking for invalid entries
df.company_size.value_counts()

company_size
S     35
L     30
M     26
XL     4
Name: count, dtype: int64

In [345]:
df.company_size.unique()

array(['L', 'S', 'XL', 'M'], dtype=object)

In [346]:
# replace invalid entries with 'M'
df.loc[df['company_size'] == 'US', 'company_size'] = 'M'
df.loc[df['company_size'] == 'XL', 'company_size'] = 'M'

In [347]:
# My Output dataframe
clean_salaries = df.copy()

### Task 2: Salary Trends by Experience

In [348]:
# group data by experience level and employment type. Then, find the average salary. All of this is then made into a dataframe.
salary_trends = pd.DataFrame(df.groupby(['experience_level', 'employment_type'])['salary_in_usd'].mean())

In [349]:
salary_trends

                                  salary_in_usd
experience_level employment_type
EN               CT                92424.000000
                 FL               160093.333333
                 FT               132732.444444
                 PT               164922.714286
EX               CT               166817.200000
                 FL               163361.250000
                 FT               175002.625000
                 PT               111243.000000
MI               CT               170696.750000
                 FL               128410.250000
                 FT               116323.750000
                 PT               131637.750000
SE               CT               127803.833333
                 FL               129452.750000
                 FT               140414.818182
                 PT               170817.666667

In [350]:
# find average salary of experience levels to get a clearer understanding
df.groupby('experience_level')['salary_in_usd'].mean().round()

experience_level
EN    143403.0
EX    163686.0
MI    136767.0
SE    142745.0
Name: salary_in_usd, dtype: float64

In [351]:
# find average salary of employment types to geta clearer understanding
df.groupby('employment_type')['salary_in_usd'].mean().round()

employment_type
CT    137291.0
FL    150251.0
FT    143890.0
PT    154126.0
Name: salary_in_usd, dtype: float64

#### Among the various experience levels, the highest earners are EX, followed by EN and SE, while MI earn the least.
#### Across experience levels, the highest earning employment types tend to be PT and FL, followed by FT while CT earns the least.

### Task 3: Remote Work Analysis

In [352]:
# First exclude remote_ratio of 50, then groupby remote_ratio, aggregate salary into mean. Finally, wrap everything into a dataframe and assign to a 
# variable.
remote_salary_comparison = pd.DataFrame(df[~(df['remote_ratio'] == 50)].groupby('remote_ratio')['salary_in_usd'].mean().rename(
    index = {100 : 'Remote', 0 : 'On-site'}))

In [353]:
remote_salary_comparison

              salary_in_usd
remote_ratio
On-site       153273.666667
Remote        145065.964286

In [354]:
# lets check how 50% on-site work compares to the other two groups
df.groupby('remote_ratio')['salary_in_usd'].mean()

remote_ratio
0      153273.666667
50     142111.750000
100    145065.964286
Name: salary_in_usd, dtype: float64

#### Remote workers earn less on average than on-site workers. We also see that those who work 50% on-site earn more than those 
#### completely remote, but less than those who work 100% on-site.

#### By: Chimeremeze Offurum